*Global Stiffness matrix for X and Y*

In [1]:
import numpy as np

In [2]:
def matrix_calculator(theta):
    K = np.array([[np.cos(theta)**2, np.sin(theta)*np.cos(theta), -np.cos(theta)**2, -np.cos(theta)*np.sin(theta) ],
                  [np.sin(theta)*np.cos(theta) , np.sin(theta)**2, -np.sin(theta)*np.cos(theta), -np.sin(theta)**2],
                  [-np.cos(theta)**2 , -np.sin(theta)*np.cos(theta), np.cos(theta)**2, np.cos(theta)*np.sin(theta)],
                  [-np.cos(theta)*np.sin(theta) , -np.sin(theta)**2, np.cos(theta)*np.sin(theta), np.sin(theta)**2]])
    return K

In [3]:
# For 90 degree
L = matrix_calculator(np.pi/2)
print(L)

[[ 3.74939946e-33  6.12323400e-17 -3.74939946e-33 -6.12323400e-17]
 [ 6.12323400e-17  1.00000000e+00 -6.12323400e-17 -1.00000000e+00]
 [-3.74939946e-33 -6.12323400e-17  3.74939946e-33  6.12323400e-17]
 [-6.12323400e-17 -1.00000000e+00  6.12323400e-17  1.00000000e+00]]


In [4]:
# For 120 degree
A = matrix_calculator((np.pi/3)*2)
print(A)

[[ 0.25      -0.4330127 -0.25       0.4330127]
 [-0.4330127  0.75       0.4330127 -0.75     ]
 [-0.25       0.4330127  0.25      -0.4330127]
 [ 0.4330127 -0.75      -0.4330127  0.75     ]]


In [5]:
# For 210 degree
D = matrix_calculator((np.pi/6) * 7)
print(D)

[[ 0.75       0.4330127 -0.75      -0.4330127]
 [ 0.4330127  0.25      -0.4330127 -0.25     ]
 [-0.75      -0.4330127  0.75       0.4330127]
 [-0.4330127 -0.25       0.4330127  0.25     ]]


In [6]:
# For 135 degree
V = matrix_calculator((np.pi/4) * 3)
print(V)

[[ 0.5 -0.5 -0.5  0.5]
 [-0.5  0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [7]:
# For 180 degree
B = matrix_calculator(np.pi)
print(B)

[[ 1.00000000e+00 -1.22464680e-16 -1.00000000e+00  1.22464680e-16]
 [-1.22464680e-16  1.49975978e-32  1.22464680e-16 -1.49975978e-32]
 [-1.00000000e+00  1.22464680e-16  1.00000000e+00 -1.22464680e-16]
 [ 1.22464680e-16 -1.49975978e-32 -1.22464680e-16  1.49975978e-32]]


In [8]:
# For 225 degree
N = matrix_calculator((np.pi/4) * 5)
print(N)

[[ 0.5  0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [-0.5 -0.5  0.5  0.5]]
