*Global Stiffness matrix for X and Y*

In [1]:
import numpy as np

In [15]:
def matrix_calculator(theta):
    K = np.array([[np.cos(theta)**2, np.sin(theta)*np.cos(theta), -np.cos(theta)**2, -np.cos(theta)*np.sin(theta) ],
                  [np.sin(theta)*np.cos(theta) , np.sin(theta)**2, -np.sin(theta)*np.cos(theta), -np.sin(theta)**2],
                  [-np.cos(theta)**2 , -np.sin(theta)*np.cos(theta), np.cos(theta)**2, np.cos(theta)*np.sin(theta)],
                  [-np.cos(theta)*np.sin(theta) , -np.sin(theta)**2, np.cos(theta)*np.sin(theta), np.sin(theta)**2]])
    return K

In [16]:
L = matrix_calculator(np.pi/2)
print(L)

[[ 3.74939946e-33  6.12323400e-17 -3.74939946e-33 -6.12323400e-17]
 [ 6.12323400e-17  1.00000000e+00 -6.12323400e-17 -1.00000000e+00]
 [-3.74939946e-33 -6.12323400e-17  3.74939946e-33  6.12323400e-17]
 [-6.12323400e-17 -1.00000000e+00  6.12323400e-17  1.00000000e+00]]


In [5]:
A = matrix_calculator((np.pi/3)*2)
print(A)

[[ 0.25      -0.4330127 -0.25       0.4330127]
 [-0.4330127  0.75       0.4330127 -0.75     ]
 [-0.25       0.4330127  0.25      -0.4330127]
 [ 0.4330127 -0.75      -0.4330127  0.75     ]]


In [7]:
D = matrix_calculator((np.pi/6) * 7)
print(D)

[[ 0.75       0.4330127 -0.75      -0.4330127]
 [ 0.4330127  0.25      -0.4330127 -0.25     ]
 [-0.75      -0.4330127  0.75       0.4330127]
 [-0.4330127 -0.25       0.4330127  0.25     ]]


In [4]:
S = matrix_calculator((np.pi/2))
print(S)

[[ 3.74939946e-33  6.12323400e-17 -3.74939946e-33 -6.12323400e-17]
 [ 6.12323400e-17  1.00000000e+00 -6.12323400e-17 -1.00000000e+00]
 [-3.74939946e-33 -6.12323400e-17  3.74939946e-33  6.12323400e-17]
 [-6.12323400e-17 -1.00000000e+00  6.12323400e-17  1.00000000e+00]]


In [95]:
# For 135 degree
V = matrix_calculator((np.pi/4) * 3)

In [96]:
print(V)

[[ 0.5 -0.5 -0.5  0.5]
 [-0.5  0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [97]:
# For 180 degree
B = matrix_calculator(np.pi)
print(B)

[[ 1.00000000e+00 -1.22464680e-16 -1.00000000e+00  1.22464680e-16]
 [-1.22464680e-16  1.49975978e-32  1.22464680e-16 -1.49975978e-32]
 [-1.00000000e+00  1.22464680e-16  1.00000000e+00 -1.22464680e-16]
 [ 1.22464680e-16 -1.49975978e-32 -1.22464680e-16  1.49975978e-32]]


In [75]:
# For 225 degree
N = matrix_calculator((np.pi/4) * 5)
print(N)

[[ 0.5  0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [-0.5 -0.5  0.5  0.5]]


In [104]:
def stifness_matrix(k):
    K = np.array([[k, -k],
                 [-k, k]])
    return K

In [106]:
J = stifness_matrix(int(3000))
print(J)

[[ 3000 -3000]
 [-3000  3000]]


In [131]:
def alumninium(A, E, L):
    K = np.array([[(A*E)/L, -(A*E)/L, 0],
                  [-(A*E)/L, 2*(A*E)/L, -(A*E)/L],
                  [0, -(A*E)/L, (A*E)/L]])

    A = int(input("Enter the value of A: "))
    E = int(input("Enter the value of E: "))
    L = int(input("Enter the value of L: "))
    return K

In [132]:
stf = alumninium(A, E, L)
print(stf)

[[ 400. -400.    0.]
 [-400.  800. -400.]
 [   0. -400.  400.]]


In [28]:
u1 = (422*100)/(10**7)
v1 = (1570*100)/(10**7)
print("The value of u1 is: ", u1)
print("The value of v1 is: ", v1)

The value of u1 is:  0.00422
The value of v1 is:  0.0157


In [29]:
A = np.array([[1/4, -np.sqrt(3)/4],
              [-np.sqrt(3)/4, 3/4 ]])
B = np.array([[2, 0],
              [0, 0]])
C = np.array([[(3*np.sqrt(3))/4, 3/4],
              [3/4, np.sqrt(3)/4]])

D = A + B + C
print(D)

[[3.54903811 0.3169873 ]
 [0.3169873  1.1830127 ]]
